### ISSUE TITLE
Escape character issue in Python

### ISSUE THREAD

**Issue by ajitid** [dracula/visual-studio-code#26] opened 2017-04-30 21:33 UTC
Check screenshot...
![capture](https://cloud.githubusercontent.com/assets/26769888/25568158/a40d75d4-2e1a-11e7-8ddc-3f2ef0c9763a.PNG)

**Comment by dsifford** [comment] 2017-04-30 23:13
@ajitid You are the master at finding inconsistencies!

Looks like the top example you gave is an issue with the textmate scope and not the theme. When typed exactly as you wrote it, the inner string is scoped as a regexp, which is why the `\E` and `\n` are highlighted as escape sequences.

I could fix that one singular issue, but by doing that I'd be breaking several other things. So the real fix would need to be made in (I believe) the python package.

Re: lines 2 and 3  -- not 100% certain, but from a google search, it appears that \E is not valid in python.

Closing this because it's out of scope.

**Closed by dsifford** 2017-04-30 23:13 UTC

**Comment by ajitid** [comment] 2017-04-30 23:25
I don't know much about theming, but other themes don't highlight escape characters in raw string.
I know \E is not an escape character.

I don't know whether I'm helping you or annoying you, but I like Dracula theme, and that's why so many issues 😅.

**Comment by dsifford** [comment] 2017-05-01 00:16
> I don't know much about theming, but other themes don't highlight escape characters in raw string.
I know \E is not an escape character.

Yeah, unfortunately with the python textmate scopes, you either get highlighted escape characters or you don't; the scope is the same either way.

Additionally, `\E`, `\Q`, `\B`, `\X`, and anything in between is counted as an escaped character with the current textmate scopes, whether they are valid or not. The issue is the non-specific selectors used in the actual scope files and not the theme itself.

> I don't know whether I'm helping you or annoying you, but I like Dracula theme, and that's why so many issues.

Nope, not annoying at all! Keep firing away as you see inconsistencies!
