### ISSUE TITLE
Color in v2.22.2 looks brighter than v2.22.1

### ISSUE THREAD

**Issue by GoodbyeNJN** [dracula/visual-studio-code#165] opened 2020-11-23 03:25 UTC
After upgrading to v2.22.2, the color scheme of the soft theme looks brighter. I don't know if this change is expected or unexpected. Screenshot below:

![v2.22.1](https://s3.ax1x.com/2020/11/23/DJiThQ.png) 
![v2.22.2](https://s3.ax1x.com/2020/11/23/DJiotg.png)

**Comment by dsifford** [comment] 2020-11-23 14:03
Dupe of #163. This was intended. There was a bug in the build phase of the soft variant that caused comments to not actually receive any color specifications, which caused it to match the default comment color.

**Comment by GoodbyeNJN** [comment] 2020-11-23 17:03
Thank you for your reply, but on my screen, not only did I observe the abnormal color in the comment part, but all other colors appeared brighter. Is this also intended?
For example, in v2.22.2, the color of the string "4.17.5", the keyword "function", the keyword "RegExp" and the number "32" are all brighter than v2.22.1, which can be confirmed with a color picker.

**Comment by dsifford** [comment] 2020-11-23 17:35
Bug fix might have introduced another bug. I'll check on this soon.

**Closed** 2020-11-24 14:36 UTC
