### ISSUE TITLE
Latest version of vscode is inaccurate in .html file

### ISSUE THREAD

**Issue by jundge** [dracula/visual-studio-code#139] opened 2020-03-12 14:16 UTC
![BAC0CA69831FDAEC41662DC7C](https://user-images.githubusercontent.com/24717511/76530609-ef4b5480-64ae-11ea-8f0f-bed089df909b.jpg)
The color of console.log is the same as the parameter color？

**Comment by dsifford** [comment] 2020-03-25 15:16
Closing as dupe of #132

**Closed by dsifford** 2020-03-25 15:16 UTC
