### ISSUE TITLE
Color difference in TypeScript class & default class

### ISSUE THREAD

**Issue by n1ghtmare** [dracula/visual-studio-code#88] opened 2018-09-30 17:55 UTC
Hi guys, I love the theme, great job, I found a small bug (thought I might share, also I'm not sure if this is desired effect, but I'm pretty sure that's was not the behavior before), notice how `let k` is different color for both of the snippets below (this is in typescript in a `.ts` file). I'm using version `2.14.1` of the theme (the latest at the time of writing this), as well as the latest version of VSCode. 

![code](https://user-images.githubusercontent.com/3255810/46260731-d2110900-c4fa-11e8-9ab1-9c20a331b0f2.png)

**Comment by dsifford** [comment] 2018-09-30 18:51
Hi there.

This looks like a dupe of #82. The issue stems from how default exports are scoped in the tmLanguage file upstream. So the only way to fix it would be to address it there.

**Comment by n1ghtmare** [comment] 2018-09-30 19:15
Oh, I see, sorry about that, I wasn't aware. Cool, I'll open an issue upstream (if there isn't one opened already).

**Comment by dsifford** [comment] 2018-10-10 18:01
@n1ghtmare Just kidding... I think I can actually fix this rather easily... I'll push it out with the adjustments I make for the latest release (in the next few days).

**Closed** 2018-11-07 02:46 UTC
