### ISSUE TITLE
Provide ability to disable italic and bold fonts

### ISSUE THREAD

**Issue by sergeyklay** [dracula/visual-studio-code#109] opened 2019-06-26 15:14 UTC
Hello,

I would like to disable italic and bold fonts. Is it possible? If not it is my feature request.

Thank you

**Comment by dsifford** [comment] 2019-06-26 15:28
Closing as dupe of #78

**Closed by dsifford** 2019-06-26 15:28 UTC

**Comment by gibbok** [comment] 2019-10-17 12:07
@dsifford first of all, great work on the Dracula theme for code, do you have any update on #78 ?
