### ISSUE TITLE
"Border" of different color surrounding the code in the editor

### ISSUE THREAD

**Issue by FaruNL** [dracula/visual-studio-code#150] opened 2020-05-04 14:24 UTC
![vscode dracula](https://user-images.githubusercontent.com/34426099/80974970-1c4d2100-8de7-11ea-8ead-b289b551665b.png)

In the editor, it shows a weird border around the code itself, I tested with different programming languages, so it doesn't seem to be something related to the language.

I've just installed the theme recently with no special configurations changed, however here's my vscode configuration if it's any good:

```
{
    "window.titleBarStyle": "custom",
    "editor.fontFamily": "'JetBrains Mono', 'MesloLGS NF', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
    "editor.fontLigatures": true,
    "editor.fontSize": 16,
    "terminal.integrated.fontSize": 16,
    "editor.tabSize": 2,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.cursorBlinking": true,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Dracula"
}
```

Specs:
* Visual Studio Code: 144.2 (Installed through apt, not snap nor flatpak)
* OS: Ubuntu 20.04 (vscode shows: Linux x64 5.4.0-28-generic)

**Comment by dsifford** [comment] 2020-05-04 14:27
Dupe of #126 #129 

Not an issue with this theme, but [this might fix it for you](https://github.com/dracula/visual-studio-code/issues/126#issuecomment-619956306)

**Closed by dsifford** 2020-05-04 14:27 UTC
